# Generated by Django 3.2.5 on 2021-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForoComentario',
            fields=[
                ('idcom', models.AutoField(db_column='IDCom', primary_key=True, serialize=False)),
                ('comdes', models.TextField(db_column='ComDes')),
                ('comtip', models.IntegerField(db_column='ComTip')),
                ('comvis', models.IntegerField(db_column='ComVis')),
            ],
            options={
                'db_table': 'foro_comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hoscod', models.AutoField(db_column='HosCod', primary_key=True, serialize=False)),
                ('hosnom', models.CharField(db_column='HosNom', max_length=40)),
                ('hostipo', models.CharField(db_column='HosTipo', max_length=40)),
                ('hoscama', models.IntegerField(db_column='HosCama')),
                ('hosdispo', models.IntegerField(db_column='HosDispo')),
                ('hoszonId', models.CharField(db_column='HosZonId', max_length=8)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idpro', models.IntegerField(db_column='IdPro', primary_key=True, serialize=False)),
                ('pronom', models.CharField(db_column='ProNom', max_length=40)),
                ('prodis', models.IntegerField(db_column='ProDis')),
                ('procant', models.IntegerField(db_column='ProCant')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('provecod', models.AutoField(db_column='ProveCod', primary_key=True, serialize=False)),
                ('provenom', models.CharField(db_column='ProveNom', max_length=40)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usucod', models.AutoField(db_column='UsuCod', primary_key=True, serialize=False)),
                ('usunom', models.CharField(db_column='UsuNom', max_length=40)),
                ('usuape', models.CharField(db_column='UsuApe', max_length=40)),
                ('usuzon', models.CharField(db_column='UsuZon', max_length=8)),
                ('usutel', models.IntegerField(db_column='UsuTel')),
                ('usudir', models.CharField(db_column='UsuDir', max_length=40)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
