# Generated by Django 3.2.5 on 2021-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('depcod', models.IntegerField(db_column='DepCod', primary_key=True, serialize=False)),
                ('depnom', models.CharField(db_column='DepNom', max_length=40)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('discod', models.IntegerField(db_column='DisCod', primary_key=True, serialize=False)),
                ('disnom', models.CharField(db_column='DisNom', max_length=40)),
            ],
            options={
                'db_table': 'distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('procod', models.IntegerField(db_column='ProCod', primary_key=True, serialize=False)),
                ('pronom', models.CharField(db_column='ProNom', max_length=40)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
    ]
