# Generated by Django 3.2.5 on 2021-07-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_departamento_distrito_provincia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
    ]
