# Generated by Django 3.2.5 on 2021-07-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('depcod',)},
        ),
    ]
