# Generated by Django 3.2.4 on 2021-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipCliNom', models.CharField(max_length=255)),
            ],
        ),
    ]
