# Generated by Django 3.2.4 on 2021-06-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_base', '0002_tipo_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
