# Generated by Django 2.1.5 on 2020-08-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('field_name', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('areaMedica', models.CharField(choices=[('ANESTESIOLOGÍA', 'ANESTESIOLOGÍA'), ('CIRUGÍA GENERAL Y DIGESTIVA', 'CIRUGÍA GENERAL Y DIGESTIVA'), ('LABORATORIOS CLÍNICOS', 'LABORATORIOS CLÍNICOS'), ('CARDIOLOGÍA', 'CARDIOLOGÍA'), ('CIRUGÍA ORTOPÉDICA Y TRAUMATOLOGÍA', 'CIRUGÍA ORTOPÉDICA Y TRAUMATOLOGÍA'), ('RADIODIAGNÓSTICO', 'RADIODIAGNÓSTICO'), ('CUIDADOS INTENSIVOS', 'CUIDADOS INTENSIVOS'), ('DERMATOLOGÍA', 'DERMATOLOGÍA'), ('FARMACIA', 'FARMACIA'), ('DIGESTIVO', 'DIGESTIVO'), ('GINECOLOGÍA Y OBSTETRICIA', 'GINECOLOGÍA Y OBSTETRICIA'), ('MEDICINA PREVENTIVA', 'MEDICINA PREVENTIVA'), ('HEMATOLOGÍA', 'HEMATOLOGÍA'), ('OFTALMOLOGÍA', 'OFTALMOLOGÍA'), ('UROLOGÍA', 'UROLOGÍA'), ('NEUMOLOGÍA', 'NEUMOLOGÍA'), ('ONCOLOGÍA', 'ONCOLOGÍA')], max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasMedicas.Doctor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasMedicas.Paciente'),
        ),
    ]
