# Generated by Django 2.1.5 on 2020-08-02 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dni',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
