# Generated by Django 2.1.5 on 2020-08-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0002_auto_20200802_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
