# Generated by Django 2.1.5 on 2020-08-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0003_auto_20200802_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='field_name',
            new_name='hora',
        ),
    ]
